-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgmPABEStYv8vZRkhG
z7LbZnq71m36DIIjVtLz6cWkyKmgCgYIKoZIzj0DAQehRANCAARltF+4aKwdf9nl
ZfCDe/YrAuLW3psBtwl5zfEEBKPSMlagn8A8j+gNud0c2UbWWDVPYvJj5fLQYuUL
ARGz+Qw5
-----END PRIVATE KEY-----